# Generated by Django 4.2.4 on 2024-11-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('track', models.CharField(max_length=255)),
                ('job_interest', models.CharField(max_length=255)),
                ('cv_url', models.TextField()),
                ('visits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recrutier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('days', models.IntegerField()),
                ('members', models.IntegerField()),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobscanner.freelancer')),
                ('recrutier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobscanner.recrutier')),
            ],
        ),
    ]
