# Generated by Django 4.2.4 on 2024-11-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
