# Generated by Django 4.2.4 on 2024-11-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobscanner', '0003_alter_freelancer_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='recrutier',
            name='scanned_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='recrutier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_logs', to='jobscanner.recrutier'),
        ),
    ]
